"""Frases de exemplo de cada tarefa, pro classificador por embeddings
(tars_embeddings.py).

Cada pedido do usuário é comparado com estas frases pelo SIGNIFICADO: a
tarefa com as frases mais parecidas ganha. Os idiomas ficam misturados de
propósito — o modelo de embeddings é multilíngue, então um exemplo em
português também ajuda a reconhecer um pedido em alemão.

Não repetem as frases do --avaliar-classificador (idiomas/*.json,
"avaliacao"), senão a nota da avaliação sairia inflada.

Pra melhorar a detecção: acrescente frases reais que caíram na tarefa
errada. O índice é refeito sozinho quando esta lista muda."""

EXEMPLOS = {
    "visao": [
        "o que tem na minha tela agora",
        "dá uma olhada nessa janela e me diz o que ela quer",
        "clica no botão verde lá embaixo",
        "tira um print e me fala o que você vê",
        "que erro é esse que apareceu na tela",
        "passa o mouse em cima daquele menu",
        "rola a página até o final e lê o que está escrito",
        "o que diz essa notificação no canto",
        "arrasta a janela pro outro monitor",
        "vê se o download já terminou na tela",
        "look at my screen and tell me what's wrong",
        "click the blue link in the middle of the page",
        "what does this popup say",
        "take a screenshot and describe it",
        "scroll down and read the terms for me",
        "is there any error message showing right now",
        "mira mi pantalla y dime qué ves",
        "haz clic en el botón de aceptar",
        "regarde mon écran et dis-moi ce qui s'affiche",
        "clique sur le bouton en haut à droite",
        "schau auf meinen Bildschirm und sag mir, was da steht",
        "klick auf den grünen Knopf unten",
    ],
    "codigo": [
        "escreve uma função que inverte uma string",
        "meu código python dá erro de indentação",
        "como faço uma requisição http em javascript",
        "cria uma classe em java pra representar um carro",
        "explica o que esse trecho de código faz",
        "corrige esse bug no meu for",
        "faz um programa em c que lê um arquivo",
        "como uso async await no node",
        "me mostra um exemplo de regex para validar email",
        "converte esse código de python pra rust",
        "why does my loop never stop in javascript",
        "write a python function that sorts a dictionary by value",
        "fix this TypeError in my react component",
        "how do I read a csv file with pandas",
        "refactor this function to be faster",
        "write a bash script that backs up my home folder",
        "escribe una función en python que sume dos números",
        "por qué mi código da un error de índice",
        "écris une fonction javascript qui trie un tableau",
        "pourquoi mon programme python plante",
        "schreib eine Funktion in Python, die Primzahlen findet",
        "warum kompiliert mein C++ Code nicht",
    ],
    "tecnico": [
        "o pip reclama de externally managed environment",
        "como vejo os logs do systemd de ontem",
        "meu wifi não conecta depois que atualizei o ubuntu",
        "como instalo o driver da nvidia no linux mint",
        "o grub sumiu depois de instalar o windows",
        "qual comando mostra o espaço livre no disco",
        "como dou permissão de execução pra um arquivo",
        "o som parou de funcionar depois do update",
        "como adiciono um repositório ppa",
        "meu pc está lento, como vejo o que está consumindo memória",
        "flatpak ou snap, qual é melhor",
        "how do I mount an external drive from the terminal",
        "my laptop won't suspend on linux",
        "how do I install docker on debian",
        "the screen flickers after installing the new kernel",
        "what does chmod 755 mean",
        "cómo instalo un programa desde la terminal en ubuntu",
        "mi linux no detecta la impresora",
        "comment installer un paquet deb sur ubuntu",
        "mon wifi ne marche plus sous linux",
        "wie installiere ich Treiber unter Linux",
        "mein Linux bootet nicht mehr nach dem Update",
    ],
    "acao": [
        "apaga os arquivos temporários da área de trabalho",
        "abre a pasta de downloads",
        "fecha todas as janelas do navegador",
        "diminui o brilho da tela",
        "cria uma pasta chamada projetos na área de trabalho",
        "copia esse texto pra área de transferência",
        "desliga o wifi",
        "abre o gerenciador de arquivos",
        "coloca o volume no mudo",
        "abre a calculadora e faz 15 vezes 4",
        "cria um arquivo de texto com a lista de compras",
        "mute the sound",
        "open the file manager",
        "close firefox",
        "create a folder called backup in documents",
        "lower the volume to 30 percent",
        "open the calculator and add 7 and 5",
        "abre la calculadora",
        "cierra el navegador",
        "ouvre le terminal",
        "baisse le volume",
        "öffne den Dateimanager",
        "mach die Musik leiser",
    ],
    "busca": [
        "encontra reviews do galaxy s25 pra mim",
        "pesquisa o horário do jogo do flamengo",
        "qual a previsão do tempo pra amanhã",
        "procura promoções de ssd de 1 tera",
        "quem ganhou a fórmula 1 no último domingo",
        "busca o endereço da farmácia mais perto",
        "quanto está o bitcoin agora",
        "procura um vídeo ensinando a fazer pão caseiro",
        "search for cheap flights to rome",
        "look up the latest ubuntu release date",
        "find reviews of the steam deck oled",
        "what's the weather in london tomorrow",
        "¿cuánto está el dólar hoy?",
        "busca noticias sobre el mundial",
        "cherche le prix d'un iphone d'occasion",
        "trouve la météo de paris pour demain",
        "such mir Bewertungen für diesen Laptop",
        "wie wird das Wetter morgen in Berlin",
    ],
    "simples": [
        "opa, beleza?",
        "oi, tudo bem?",
        "obrigado pela ajuda",
        "entra no youtube",
        "abre o instagram",
        "até mais",
        "hello there",
        "thank you so much",
        "open instagram",
        "go to youtube",
        "hola, ¿qué tal?",
        "gracias",
        "salut, ça va ?",
        "merci beaucoup",
        "hallo, wie geht's?",
        "danke schön",
    ],
    "geral": [
        "por que o céu é azul",
        "me ajuda a escrever um e-mail pedindo folga",
        "qual a capital da austrália",
        "me conta uma curiosidade sobre o espaço",
        "como funciona a fotossíntese",
        "me dá dicas pra estudar melhor",
        "escreve uma mensagem de aniversário pra minha mãe",
        "quem foi santos dumont",
        "me sugere um livro de ficção científica",
        "explica a teoria da relatividade de um jeito simples",
        "help me write an email asking for time off",
        "why do cats purr",
        "give me ideas for a birthday party",
        "what is the meaning of the word serendipity",
        "write a short story about a robot",
        "¿por qué el mar es salado?",
        "escríbeme un poema sobre la luna",
        "explique-moi la révolution française",
        "donne-moi des idées de dîner",
        "erklär mir, wie ein Regenbogen entsteht",
        "schreib ein kurzes Gedicht über den Herbst",
    ],
}
